name: Terraform Deploy or Destroy

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose what to do: "apply" or "destroy"'
        required: true
        default: 'apply'

jobs:
  terraform:
    name: 'Terraform Apply or Destroy'
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.5.0
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply or Destroy
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action input. Must be 'apply' or 'destroy'."
            exit 1
          fi
